name: rces_final_project
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.6
    - obspy
    - basemap       # mapping package
    - cartopy       # Geographic plotting toolkit
    - haversine     # haversine great distance formula
    - h5py          # Wrapper for HDF5
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - proj4         # geographic projections
    - pyresample    # Geographic resampling tools
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - scikit-image  # Image processing routines
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library
